"""Run non-Claude models through a private CLIProxyAPI instance.

`claude plugin eval` only knows how to run `claude -p`, and `claude -p` only speaks the
Anthropic Messages API. CLIProxyAPI (router-for-me/CLIProxyAPI) serves that API on
localhost and translates to OpenAI-compatible upstreams such as Venice. skillbench starts
one instance per run on a free localhost port with a generated config: the upstream key
is fetched from its secret reference, written to a 0600 file only for the life of the
run, and deleted afterwards. Model ids are ``<provider>/<model>``; the proxy's ``prefix``
routes them, and the pinned Claude judge keeps going to Anthropic through a
``claude-api-key`` entry when one is configured.
"""

from __future__ import annotations

import json
import os
import secrets
import shutil
import socket
import subprocess
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

from .config import Config, Provider
from .secrets import describe, resolve


class ProxyError(RuntimeError):
    pass


def split_model(model: str, config: Config) -> tuple[str | None, str]:
    """``venice/kimi-k3`` -> (``venice``, ``kimi-k3``) when ``venice`` is a configured provider."""
    if "/" in model:
        prefix, rest = model.split("/", 1)
        if prefix in config.providers:
            return prefix, rest
    return None, model


def group_by_provider(models: list[str], config: Config) -> dict[str | None, list[str]]:
    groups: dict[str | None, list[str]] = {}
    for model in models:
        provider, _ = split_model(model, config)
        groups.setdefault(provider, []).append(model)
    return groups


def free_port() -> int:
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def _yaml_str(value: str) -> str:
    return json.dumps(value)


def render_config(
    *,
    port: int,
    token: str,
    auth_dir: Path,
    providers: list[tuple[Provider, list[str], str]],
    judge_api_key: str | None,
    debug: bool = False,
) -> str:
    """CLIProxyAPI YAML for one run: localhost only, one client token, no management API."""
    lines = [
        "# generated by skillbench for a single run; contains upstream secrets; deleted on exit",
        'host: "127.0.0.1"',
        f"port: {port}",
        f"auth-dir: {_yaml_str(str(auth_dir))}",
        "api-keys:",
        f"  - {_yaml_str(token)}",
        "remote-management:",
        "  allow-remote: false",
        '  secret-key: ""',
        "  disable-control-panel: true",
        "  disable-auto-update-panel: true",
        f"debug: {'true' if debug else 'false'}",
        "logging-to-file: false",
        "usage-statistics-enabled: false",
    ]
    if judge_api_key:
        lines += ["claude-api-key:", f"  - api-key: {_yaml_str(judge_api_key)}"]
    if providers:
        lines.append("openai-compatibility:")
        for provider, models, key in providers:
            lines += [
                f"  - name: {_yaml_str(provider.name)}",
                f"    prefix: {_yaml_str(provider.name)}",
                f"    base-url: {_yaml_str(provider.base_url)}",
                "    api-key-entries:",
                f"      - api-key: {_yaml_str(key)}",
                "    models:",
            ]
            for model in models:
                lines += [f"      - name: {_yaml_str(model)}", f"        alias: {_yaml_str(model)}"]
    return "\n".join(lines) + "\n"


@dataclass
class ProxyHandle:
    port: int
    token: str
    config_path: Path
    log_path: Path
    process: subprocess.Popen = field(repr=False)
    providers: tuple[str, ...] = ()
    judge_routed: bool = False

    @property
    def base_url(self) -> str:
        return f"http://127.0.0.1:{self.port}"

    def env(self, model: str | None = None) -> dict[str, str]:
        # Claude Code sends ANTHROPIC_AUTH_TOKEN as the bearer; the proxy checks it against
        # its api-keys list. Background calls (titles, summaries) default to a Haiku id the
        # proxy cannot route, so they are pointed at the model under test.
        env = {"ANTHROPIC_BASE_URL": self.base_url, "ANTHROPIC_AUTH_TOKEN": self.token}
        if model:
            env["ANTHROPIC_DEFAULT_HAIKU_MODEL"] = model
            env["ANTHROPIC_SMALL_FAST_MODEL"] = model
        return env

    def stop(self) -> None:
        if self.process.poll() is None:
            self.process.terminate()
            try:
                self.process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self.process.kill()
        # The config holds upstream keys in plaintext; it exists only while the proxy runs.
        self.config_path.unlink(missing_ok=True)


def _healthy(base_url: str, token: str) -> bool:
    req = urllib.request.Request(
        f"{base_url}/v1/models", headers={"Authorization": f"Bearer {token}"}
    )
    try:
        with urllib.request.urlopen(req, timeout=2) as resp:
            return resp.status == 200
    except (urllib.error.URLError, OSError, ValueError):
        return False


def list_models(base_url: str, token: str) -> list[str]:
    req = urllib.request.Request(
        f"{base_url}/v1/models", headers={"Authorization": f"Bearer {token}"}
    )
    with urllib.request.urlopen(req, timeout=5) as resp:
        data = json.loads(resp.read())
    return sorted(m.get("id", "") for m in data.get("data", []))


def start_proxy(
    config: Config,
    provider_models: dict[str, list[str]],
    *,
    extra_models: tuple[str, ...] = (),
    log_dir: Path | None = None,
    debug: bool = False,
) -> ProxyHandle:
    """Resolve secrets, write the private config, launch cliproxyapi, and wait until it answers.

    ``extra_models`` (typically the judge) join a provider's alias list when they carry that
    provider's prefix, so ``--judge-model venice/claude-sonnet-4-5`` resolves too.
    """
    binary = shutil.which(config.proxy.binary)
    if binary is None:
        raise ProxyError(
            f"{config.proxy.binary!r} not found; provider models need CLIProxyAPI "
            "(brew install cliproxyapi) or set [proxy] binary"
        )
    op_account = config.proxy.op_account
    providers: list[tuple[Provider, list[str], str]] = []
    for name, models in provider_models.items():
        provider = config.providers[name]
        key = resolve(provider.api_key, op_account=op_account)
        wanted = list(models) + [m for m in extra_models if split_model(m, config)[0] == name]
        bare = list(dict.fromkeys(split_model(m, config)[1] for m in wanted))
        providers.append((provider, bare, key))
    judge_key = (
        resolve(config.proxy.judge_api_key, op_account=op_account)
        if config.proxy.judge_api_key
        else None
    )

    workdir = config.build_dir / "proxy"
    workdir.mkdir(parents=True, exist_ok=True)
    auth_dir = workdir / "auth"
    auth_dir.mkdir(exist_ok=True)
    port = free_port()
    token = "skillbench-" + secrets.token_urlsafe(24)
    config_path = workdir / f"config-{port}.yaml"
    fd = os.open(config_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as handle:
        handle.write(
            render_config(
                port=port,
                token=token,
                auth_dir=auth_dir,
                providers=providers,
                judge_api_key=judge_key,
                debug=debug,
            )
        )
    log_path = (log_dir or workdir) / f"cliproxyapi-{port}.log"
    log = log_path.open("w")
    process = subprocess.Popen(
        [binary, "-config", str(config_path)], stdout=log, stderr=subprocess.STDOUT, cwd=workdir
    )
    proxy = ProxyHandle(
        port=port,
        token=token,
        config_path=config_path,
        log_path=log_path,
        process=process,
        providers=tuple(provider_models),
        judge_routed=judge_key is not None,
    )
    deadline = time.monotonic() + 20
    while time.monotonic() < deadline:
        if process.poll() is not None:
            proxy.stop()
            tail = "\n".join(log_path.read_text(errors="replace").splitlines()[-10:])
            raise ProxyError(f"cliproxyapi exited early (code {process.returncode}):\n{tail}")
        if _healthy(proxy.base_url, token):
            return proxy
        time.sleep(0.25)
    proxy.stop()
    raise ProxyError(f"cliproxyapi did not answer on {proxy.base_url} within 20s; see {log_path}")


def describe_sources(config: Config, provider_models: dict[str, list[str]]) -> list[str]:
    out = [f"{name}: {describe(config.providers[name].api_key)}" for name in provider_models]
    if config.proxy.judge_api_key:
        out.append(f"judge (Anthropic): {describe(config.proxy.judge_api_key)}")
    return out
